### ISSUE TITLE
I have got an error message "Chart download failed."

### ISSUE THREAD

**Issue by Mars2105** [codevise/pageflow-chart#8]
Hello,

I have got always an error message "Chart download failed." after typing a diagramm URL, e.g. for URL http://cf.datawrapper.de/d02Bg/1/

This URL is correct. How can I eliminate this error. I have a very little knowlidges about ruby on rails.

![error](https://cloud.githubusercontent.com/assets/12431363/8477557/52289f86-20cb-11e5-96f9-1a7ce36d7939.jpg)

My apache settings are
![apache_settings](https://cloud.githubusercontent.com/assets/12431363/8477659/2765d808-20cc-11e5-8499-3f1bfb76568c.jpg)

Many thanks for your help.
Slava

**Comment by tf** [comment]
Hi Slava,

please have a look in the log file of the background worker scraping the charts: `log/jobs/production/scraping.log`. 

Datawrapper changed their URL scheme recently. Newly generated charts have URLs starting with `datawrapper.dwcdn.net`. The old datawrapper charts cause a connection refused error, while trying to access `http://piwik.datawrapper.de/piwik.js`. I also see that error in the DevTools console when I open your chart URL in Chrome.

In my case that error caused scraping of charts to fail.

To use the new datawrapper URL scheme, you need to add it to the list of supported hosts in the `pageflow-chart` initializer. I'll update the README now since I think it is not yet mentioned there.

Cheers

**Comment by Mars2105** [comment]
Many thanks for your answer.

We have the problem resolved.

Strange but the version of pageflow-chart folder has other content of files
as on this page https://github.com/codevise/pageflow-chart

For this reason I have replaced the folder "pageflow-chart" completely with
the last GIT version (gem version 0.1.0)

$ cd /var/lib/gems/2.1.0/gems
$ rm -Rf pageflow-chart-0.1.0/
$ git clone https://github.com/codevise/pageflow-chart.git
 pageflow-chart-0.1.0
$ cd  pageflow-chart-0.1.0
$ ls -l
$ service apache2 restart

Many thanks for your support.

On Thu, Jul 2, 2015 at 3:23 PM, Tim Fischbach <notifications@github.com>
wrote:

> Hi Slava,
>
> please have a look in the log file of the background worker scraping the
> charts: log/jobs/production/scraping.log.
>
> Datawrapper changed their URL scheme recently. Newly generated charts have
> URLs starting with datawrapper.dwcdn.net. The old datawrapper charts
> cause a connection refused error, while trying to access
> http://piwik.datawrapper.de/piwik.js. I also see that error in the
> DevTools console when I open your chart URL in Chrome.
>
> In my case that error caused scraping of charts to fail.
>
> To use the new datawrapper URL scheme, you need to add it to the list of
> supported hosts in the pageflow-chart initializer. I'll update the README
> now since I think it is not yet mentioned there.
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codevise/pageflow-chart/issues/8#issuecomment-118030994>
> .
>



-- 
Mit freundlichen Grüßen
Vyacheslav Gromov

**Comment by Mars2105** [comment]
Can I use this URL?
https://charts.datawrapper.de/LCHQB/index.html

**Comment by tf** [comment]
You have add a new supported host in the initializer. See the updated README (configuration section)

I've now released v0.1.1, before there were some yet unreleased changes in the github repository. If you wish to use an upstream version straight from github again in the future, I'd suggest using [bundler's git support](http://bundler.io/v1.10/git.html) instead of tinkering with the gem folder manually.

**Comment by Mars2105** [comment]
Like this?
File config/initializers/pageflow_chart.rb

Pageflow::Chart.configure do |config|
  config.scraped_sites_root_url = '/datawrapper'

  # Allow scraping charts from custom account URLs
  config.supported_hosts << 'http://charts.datawrapper.de'
end

**Comment by Mars2105** [comment]
Which command must I use?
gem update pageflow-chart or other?

**Comment by tf** [comment]
Yes.

**Comment by tf** [comment]
No. You have to use bundler. Please understand that we can not provide support for general Ruby on Rails questions in this context.

Have a look at the [Updating Pageflow wiki page](https://github.com/codevise/pageflow/wiki/Updating-Pageflow). The steps there also apply to other pageflow gems like this one. Also have a look at the [bundler docs](http://bundler.io/) for more background info.

**Comment by Mars2105** [comment]
Thank you.
gem 'pageflow-chart', git: 'https://github.com/codevise/pageflow-chart.git'

**Comment by tf** [comment]
Or simply `gem 'pageflow-chart'` in the `Gemfile` and then `bundle update pageflow-chart` to update the `Gemfile.lock`.

**Comment by Mars2105** [comment]
Many thanks! It works!

**Comment by tf** [comment]
Great. I'll close this issue then.
